language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - ~/.npm
        - ./node_modules
        - ~/.cache
    override:
        - npm ci
branches:
  only:
    - main
before_script:
    - npm install -g @angular/cli
script:
    - npm install
    - npm run compodoc
after_success:
  - bash ./scripts/deploy.sh
