language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - ~/.npm
        - ./node_modules
        - ~/.cache
    override:
        - npm ci
branches:
  only:
    - main
before_script:
    - npm install -g @angular/cli
install:
  - npm install

jobs:
  include:
    - stage: Build and deploy documentation
      script:
        - npm run compodoc
      after_success:
        - bash ./scripts/deploy.sh
    - stage: npm release
      script: npm run build:lib
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true

