language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - ~/.npm
        - ./node_modules
        - ~/.cache
    override:
        - npm ci
        - npm run cy:verify
before_script:
    - npm install -g @angular/cli
script:
    - npm install
    - npm compodoc
    -
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./docs
  on:
    branch: main
